### ISSUE TITLE
Won't run - Syntax error

### ISSUE THREAD

**Issue by LeeUnd** [ostera/tldr.jsx#103]
I can't get this to run at all. This is the error I receive:

/usr/local/lib/node_modules/tldr/bin/tldr:34
program.on('--help', () => {
^
SyntaxError: Unexpected token )
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:902:3

I am running Ubuntu 14.04

**Comment by ostera** [comment]
Oh hey @LeeUnd, this is the web client :) for the node client I think you're looking for https://github.com/tldr-pages/tldr-node-client
